export const selectCars = (state) => state.cars.cars;
export const selectIsLoading = (state) => state.cars.isLoading;
export const selectIsError = (state) => state.cars.isError;
export const selectQuery = (state) => state.cars.query;
export const selectPage = (state) => state.cars.page;
export const selectTotalPages = (state) => state.cars.totalPages;
export const selectedBrands = (state) => state.cars.brands;
export const selectPrices = (state) => state.cars.rentalPrice;
export const selectSelectedCar = (state) => state.cars.selectedCar;
